Repository redacademy/MinervaSummer2019, pull requests merged in 2019-09, with the labels that each got.

#13 Add GraphCool
  README.md
  server/.graphcoolrc
  server/graphcool.yml
  server/package.json
  server/src/email-password/authenticate.graphql
  server/src/email-password/authenticate.ts
  server/src/email-password/loggedInUser.graphql
  server/src/email-password/loggedInUser.ts
  server/src/email-password/signup.graphql
  server/src/email-password/signup.ts
  server/src/hello.graphql
  server/src/hello.js
  server/types.graphql
  server/yarn.lock
Labels: enhancement

#14 Added external packages
  Client/.eslintrc.js
  Client/package.json
  Client/yarn.lock
Labels: enhancement

#16 Navigation and basic routing
  client/ios/Podfile.lock
  client/js/App.js
  client/js/components/AuthLoadingScreen/AuthLoadingScreen.js
  client/js/components/AuthLoadingScreen/index.js
  client/js/components/AuthLoadingScreen/styles.js
  client/js/components/CircularLoader/CircularLoader.js
  client/js/components/CircularLoader/index.js
  client/js/components/CircularLoader/styles.js
  client/js/navigation/AppStackNavigation.js
  client/js/navigation/RootStackNavigation.js
  client/js/screens/AllChats/AllChats.js
  client/js/screens/AllChats/AllChatsContainer.js
  client/js/screens/Community/Community.js
  client/js/screens/Community/CommunityContainer.js
  client/js/screens/Connections/Connections.js
  client/js/screens/Connections/ConnectionsContainer.js
  client/js/screens/Login/LoginContainer.js
  client/js/screens/Login/index.js
  client/js/screens/SignIn/SignIn.js
  client/js/screens/SignIn/SignInContainer.js
  client/js/screens/SignIn/index.js
  client/js/screens/SignIn/styles.js
  client/js/screens/YourProfile/YourProfile.js
  client/js/screens/YourProfile/YourProfileContainer.js
  client/package.json
  client/yarn.lock
Labels: enhancement

#18 Added apollo provider
  client/js/App.js
  client/js/config/apollo/index.js
  client/package.json
  client/yarn.lock
Labels: enhancement

#19 Sign In
  .gitignore
  client/android/app/build.gradle
  client/android/app/src/main/assets/fonts/AntDesign.ttf
  client/android/app/src/main/assets/fonts/Entypo.ttf
  client/android/app/src/main/assets/fonts/EvilIcons.ttf
  client/android/app/src/main/assets/fonts/Feather.ttf
  client/android/app/src/main/assets/fonts/FontAwesome.ttf
  client/android/app/src/main/assets/fonts/FontAwesome5_Brands.ttf
  client/android/app/src/main/assets/fonts/FontAwesome5_Regular.ttf
  client/android/app/src/main/assets/fonts/FontAwesome5_Solid.ttf
  client/android/app/src/main/assets/fonts/Fontisto.ttf
  client/android/app/src/main/assets/fonts/Foundation.ttf
  client/android/app/src/main/assets/fonts/Ionicons.ttf
  client/android/app/src/main/assets/fonts/MaterialCommunityIcons.ttf
  client/android/app/src/main/assets/fonts/MaterialIcons.ttf
  client/android/app/src/main/assets/fonts/Octicons.ttf
  client/android/app/src/main/assets/fonts/SimpleLineIcons.ttf
  client/android/app/src/main/assets/fonts/Zocial.ttf
  client/android/app/src/main/java/com/minervasummer2019/MainApplication.java
  client/android/settings.gradle
  client/ios/MinervaSummer2019.xcodeproj/project.pbxproj
  client/ios/MinervaSummer2019/Info.plist
  client/ios/Podfile
  client/ios/Podfile.lock
  client/js/components/GradientButton/GradientButton.js
  client/js/components/GradientButton/index.js
  client/js/components/GradientButton/styles.js
  client/js/config/theme.js
  client/js/navigation/RootStackNavigation.js
  client/js/screens/SignIn/SignIn.js
  client/js/screens/SignIn/SignInContainer.js
  client/js/screens/SignIn/styles.js
  client/js/screens/Welcome/Welcome.js
  client/js/screens/Welcome/WelcomeContainer.js
  client/js/screens/Welcome/index.js
  client/js/screens/Welcome/styles.js
  client/package.json
  client/yarn.lock
  package-lock.json
Labels: enhancement

#24 Connections Screen
  client/js/components/AuthLoadingScreen/AuthLoadingScreen.js
  client/js/components/GradientButton/styles.js
  client/js/components/UserCard/UserCard.js
  client/js/components/UserCard/index.js
  client/js/components/UserCard/styles.js
  client/js/config/models.js
  client/js/screens/Connections/Connections.js
  client/js/screens/Connections/ConnectionsContainer.js
  client/js/screens/Connections/styles.js
  client/js/screens/SignIn/SignIn.js
Labels: enhancement

#23 PostList Component
  client/ios/MinervaSummer2019/Images.xcassets/AppIcon.appiconset/Contents.json
  client/js/components/PostList/PostList.js
  client/js/components/PostList/index.js
  client/js/components/PostList/styles.js
  client/js/config/model.js
  client/js/config/theme.js
  client/js/context/FavesContext/FavesContext.js
  client/js/context/FavesContext/index.js
  client/js/lib/helper.js
  client/js/navigation/AppStackNavigation.js
  client/js/screens/Community/Community.js
  client/js/screens/Community/CommunityContainer.js
  client/package.json
  client/yarn.lock
  package-lock.json
  server/package.json
  server/src/email-password/authenticate.ts
  server/types.graphql
  server/yarn.lock
Labels: enhancement

#36 Bugfix: Stack Navigation
  client/js/components/UserCard/UserCard.js
  client/js/components/UserCard/styles.js
  client/js/navigation/AppStackNavigation.js
  client/js/navigation/RootStackNavigation.js
  client/js/screens/Welcome/WelcomeContainer.js
  client/js/screens/YourProfile.deprecated/YourProfile.js
  client/js/screens/YourProfile.deprecated/YourProfileContainer.js
  client/js/screens/YourProfile.deprecated/index.js
  client/js/screens/YourProfile.deprecated/styles.js
Labels: bug

#37 Minor UI/UX improvements
  client/js/assets/PNG/additional_illustrations/connections@1x.png
  client/js/assets/PNG/additional_illustrations/connections@2x.png
  client/js/assets/PNG/additional_illustrations/connections@3x.png
  client/js/assets/PNG/ways_to_meet/after_school_active.png
  client/js/assets/PNG/ways_to_meet/after_school_active@1x.png
  client/js/assets/PNG/ways_to_meet/after_school_active@2x.png
  client/js/assets/PNG/ways_to_meet/after_school_active@4x.png
  client/js/assets/PNG/ways_to_meet/after_school_inactive.png
  client/js/assets/PNG/ways_to_meet/after_school_inactive@1x.png
  client/js/assets/PNG/ways_to_meet/after_school_inactive@2x.png
  client/js/assets/PNG/ways_to_meet/after_school_inactive@4x.png
  client/js/assets/PNG/ways_to_meet/coffee_active.png
  client/js/assets/PNG/ways_to_meet/coffee_active@1x.png
  client/js/assets/PNG/ways_to_meet/coffee_active@2x.png
  client/js/assets/PNG/ways_to_meet/coffee_active@4x.png
  client/js/assets/PNG/ways_to_meet/coffee_inactive.png
  client/js/assets/PNG/ways_to_meet/coffee_inactive@1x.png
  client/js/assets/PNG/ways_to_meet/coffee_inactive@2x.png
  client/js/assets/PNG/ways_to_meet/coffee_inactive@4x.png
  client/js/assets/PNG/ways_to_meet/lunch_active.png
  client/js/assets/PNG/ways_to_meet/lunch_active@1x.png
  client/js/assets/PNG/ways_to_meet/lunch_active@2x.png
  client/js/assets/PNG/ways_to_meet/lunch_active@4x.png
  client/js/assets/PNG/ways_to_meet/lunch_inactive.png
  client/js/assets/PNG/ways_to_meet/lunch_inactive@1x.png
  client/js/assets/PNG/ways_to_meet/lunch_inactive@2x.png
  client/js/assets/PNG/ways_to_meet/lunch_inactive@4x.png
  client/js/assets/PNG/ways_to_meet/walk_active.png
  client/js/assets/PNG/ways_to_meet/walk_active@1x.png
  client/js/assets/PNG/ways_to_meet/walk_active@2x.png
  client/js/assets/PNG/ways_to_meet/walk_active@4x.png
  client/js/assets/PNG/ways_to_meet/walk_inactive.png
  client/js/assets/PNG/ways_to_meet/walk_inactive@1x.png
  client/js/assets/PNG/ways_to_meet/walk_inactive@2x.png
  client/js/assets/PNG/ways_to_meet/walk_inactive@4x.png
  client/js/components/GradientButton/styles.js
  client/js/config/models.js
  client/js/screens/AccountForm/AccountForm.js
  client/js/screens/AccountForm/styles.js
  client/js/screens/Connections/Connections.js
  client/js/screens/Connections/ConnectionsContainer.js
  client/js/screens/Connections/styles.js
  client/js/screens/LookingForForm/LookingForForm.js
  client/js/screens/LookingForForm/styles.js
  client/js/screens/ProfessionalInterestsForm/ProfessionalInterestsForm.js
  client/js/screens/ProfileForm/ProfileForm.js
  client/js/screens/ProfileForm/ProfileFormContainer.js
  client/js/screens/ProfileForm/styles.js
  client/js/screens/SignIn/SignIn.js
  client/js/screens/SignIn/styles.js
  client/js/screens/UserProfile/UserProfileContainer.js
  client/js/screens/UserProfile/styles.js
  client/js/screens/Welcome/styles.js
Labels: enhancement

#38 Comments Component
  client/js/components/CommentList/CommentList.js
  client/js/components/CommentList/index.js
  client/js/components/CommentList/styles.js
  client/js/components/PostList/PostList.js
  client/js/config/model.js
  client/js/navigation/AppStackNavigation.js
  client/js/screens/Comments/Comments.js
  client/js/screens/Comments/CommentsContainer.js
  client/js/screens/Comments/styles.js
  client/js/screens/Community/CommunityContainer.js
  server/types.graphql
Labels: enhancement

#40 FavesContext
  client/js/App.js
  client/js/assets/PNG/additional_illustrations/favourite@1x.png
  client/js/assets/PNG/additional_illustrations/favourite@2x.png
  client/js/assets/PNG/additional_illustrations/favourite@3x.png
  client/js/components/PostList/PostList.js
  client/js/components/PostList/styles.js
  client/js/config/models.js
  client/js/context/FavesContext/FavesContext.js
  client/js/context/FavesContext/index.js
  client/js/navigation/AppStackNavigation.js
  client/js/screens/Community/Community.js
  client/js/screens/Community/CommunityContainer.js
  client/js/screens/Connections/ConnectionsContainer.js
  client/js/screens/ProfessionalInterestsForm/ProfessionalInterestsForm.js
  client/js/screens/SignIn/SignIn.js
Labels: enhancement

#41 Suggested Filter
  client/js/components/AuthLoadingScreen/AuthLoadingScreen.js
  client/js/components/CircularLoader/styles.js
  client/js/context/FavesContext/FavesContext.js
  client/js/screens/Connections/Connections.js
  client/js/screens/Connections/ConnectionsContainer.js
  client/js/screens/PersonalInterestsForm/PersonalInterestsForm.js
  client/js/screens/PersonalInterestsForm/styles.js
  client/js/screens/ProfessionalInterestsForm/ProfessionalInterestsForm.js
  client/js/screens/SignIn/SignIn.js
Labels: enhancement

#39 add createComment feature
  client/js/components/CommentList/CommentList.js
  client/js/components/CommentList/styles.js
  client/js/components/CreateComment/CreateComment.js
  client/js/components/CreateComment/index.js
  client/js/components/CreateComment/styles.js
  client/js/components/PostList/PostList.js
  client/js/screens/Comments/Comments.js
  client/js/screens/Comments/styles.js
Labels: enhancement

#43 added favourite posts screen
  client/js/navigation/AppStackNavigation.js
  client/js/screens/Community/CommunityContainer.js
  client/js/screens/Community/styles.js
  client/js/screens/Favourites/Favourites.js
  client/js/screens/Favourites/FavouritesContainer.js
  client/js/screens/Favourites/styles.js
Labels: enhancement

#53 Gather Queries
  client/js/assets/PNG/navigation_bar/chat_blue.png
  client/js/assets/PNG/navigation_bar/chat_light_grey.png
  client/js/assets/PNG/navigation_bar/community_blue.png
  client/js/assets/PNG/navigation_bar/community_light_grey.png
  client/js/assets/PNG/navigation_bar/connections_blue.png
  client/js/assets/PNG/navigation_bar/connections_light_grey.png
  client/js/assets/PNG/navigation_bar/profile_blue.png
  client/js/assets/PNG/navigation_bar/profile_light_grey.png
  client/js/components/AuthLoadingScreen/AuthLoadingScreen.js
  client/js/components/CommentList/CommentList.js
  client/js/components/CreateComment/CreateComment.js
  client/js/components/CreateComment/styles.js
  client/js/components/PostList/PostList.js
  client/js/components/PostList/styles.js
  client/js/config/apollo/queries.js
  client/js/config/theme.js
  client/js/navigation/AppStackNavigation.js
  client/js/navigation/config.js
  client/js/navigation/styles.js
  client/js/screens/Community/Community.js
  client/js/screens/Community/CommunityContainer.js
  client/js/screens/Community/styles.js
  client/js/screens/Connections/ConnectionsContainer.js
  client/js/screens/CreatePost/CreatePost.js
  client/js/screens/Favourites/FavouritesContainer.js
  client/js/screens/PersonalInterestsForm/PersonalInterestsFormContainer.js
  client/js/screens/ProfessionalInterestsForm/ProfessionalInterestsForm.js
  client/js/screens/ProfessionalInterestsForm/ProfessionalInterestsFormContainer.js
  client/js/screens/SignIn/SignIn.js
  server/types.graphql
Labels: enhancement

#50 Alex feature user profile
  client/index.js
  client/js/assets/PNG/Profile_icons/Location@3x.png
  client/js/assets/PNG/Profile_icons/Location@3x@1x.png
  client/js/assets/PNG/Profile_icons/Location@3x@2x.png
  client/js/assets/PNG/Profile_icons/icon_city.png
  client/js/assets/PNG/Profile_icons/icon_city@4x.png
  client/js/assets/PNG/Profile_icons/icon_city@6x.png
  client/js/assets/PNG/Profile_icons/icon_invisible@3x.png
  client/js/assets/PNG/Profile_icons/icon_invisible@3x@2x.png
  client/js/assets/PNG/Profile_icons/icon_invisible@3x@4x.png
  client/js/assets/PNG/Profile_icons/icon_invisible_light_grey@3x.png
  client/js/assets/PNG/Profile_icons/icon_invisible_light_grey@3x@2x.png
  client/js/assets/PNG/Profile_icons/icon_invisible_light_grey@3x@4x.png
  client/js/assets/PNG/Profile_icons/icon_school.png
  client/js/assets/PNG/Profile_icons/icon_school@4x.png
  client/js/assets/PNG/Profile_icons/icon_school@6x.png
  client/js/assets/PNG/Profile_icons/icon_visible@3x.png
  client/js/assets/PNG/Profile_icons/icon_visible@3x@2x.png
  client/js/assets/PNG/Profile_icons/icon_visible@3x@4x.png
  client/js/assets/PNG/Profile_icons/icon_visible_light_grey@3x.png
  client/js/assets/PNG/Profile_icons/icon_visible_light_grey@3x@2x.png
  client/js/assets/PNG/Profile_icons/icon_visible_light_grey@3x@4x.png
  client/js/assets/PNG/extras/Profile2x.png
  client/js/components/GradientButton/GradientButton.js
  client/js/components/GradientButton/styles.js
  client/js/components/UserProfile/FaveWays.js
  client/js/components/UserProfile/InterestButton.js
  client/js/components/UserProfile/selector.js
  client/js/config/apollo/queries.js
  client/js/context/FavesContext/FavesContext.js
  client/js/lib/helpers/interest_function.js
  client/js/navigation/AppStackNavigation.js
  client/js/screens/LookingForForm/LookingForForm.js
  client/js/screens/UserProfile/UserProfile.js
  client/js/screens/UserProfile/UserProfileContainer.js
  client/js/screens/UserProfile/helpers/FaveWays.js
  client/js/screens/UserProfile/helpers/InterestButton.js
  client/js/screens/UserProfile/styles.js
Labels: Epic, enhancement

#60 Alex feature sign out
  client/js/assets/PNG/additional_illustrations/attention@1x.png
  client/js/assets/PNG/additional_illustrations/attention@2x.png
  client/js/assets/PNG/additional_illustrations/attention@3x.png
  client/js/components/UserProfile/signOutModal.js
  client/js/screens/UserProfile/UserProfile.js
  client/js/screens/UserProfile/UserProfileContainer.js
  client/js/screens/UserProfile/styles.js
Labels: enhancement

#61 Adding the error handling when the user cant be logged in
  client/js/screens/SignIn/SignIn.js
  client/js/screens/SignIn/styles.js
Labels: enhancement

#64 Fixed app crashing due to app icon
  client/ios/MinervaSummer2019.xcodeproj/project.pbxproj
  client/ios/MinervaSummer2019/Images.xcassets/AppIcon.appiconset/minerva_icon-1.jpg
  client/ios/MinervaSummer2019/Images.xcassets/AppIcon.appiconset/minerva_icon-2.jpg
  client/ios/MinervaSummer2019/Images.xcassets/AppIcon.appiconset/minerva_icon.jpg
  client/js/assets/PNG/minerva_logos/minerva_icon.jpg
Labels: bug

#66 Bugfix with FavesContext
  client/js/components/AddToChatModal/AddToChatModal.js
  client/js/components/AddToChatModal/styles.js
  client/js/components/AuthLoadingScreen/AuthLoadingScreen.js
  client/js/components/ChatCard/ChatCard.js
  client/js/components/ChatCard/styles.js
  client/js/components/StartChatModal/StartChatModal.js
  client/js/components/UserCard/UserCard.js
  client/js/components/UserCard/styles.js
  client/js/config/apollo/queries.js
  client/js/navigation/AppStackNavigation.js
  client/js/screens/AllChats/styles.js
  client/js/screens/Connections/Connections.js
  client/js/screens/Connections/ConnectionsContainer.js
  client/js/screens/Connections/styles.js
  client/js/screens/CreatePost/styles.js
  client/js/screens/ProfileForm/ProfileForm.js
  client/js/screens/ProfileForm/styles.js
  client/js/screens/SingleChat/SingleChat.js
  client/js/screens/SingleChat/SingleChatContainer.js
  client/js/screens/SingleChat/styles.js
  client/js/screens/UserProfile/UserProfile.js
  client/js/screens/UserProfile/styles.js
Labels: enhancement

#70 moved favourites buttton off header
  client/js/components/ChatCard/ChatCard.js
  client/js/components/PostList/PostList.js
  client/js/navigation/AppStackNavigation.js
  client/js/screens/Community/Community.js
  client/js/screens/Community/CommunityContainer.js
  client/js/screens/Community/styles.js
  client/js/screens/UserProfile/UserProfile.js
  client/js/screens/UserProfile/styles.js
Labels: bug
